### ISSUE TITLE
ocNews not updating after latest Sailfish OS update to 1.1.4.29

### ISSUE THREAD

**Issue by rednaxela-work** [Buschtrommel/ocNews#64] opened 2015-05-06 12:11 UTC
Hello,

ocNews is great and worked fine with my OwnCloud installation until yesterday's Sailfish OS upgrade.
After this it isn't able to synchronize with the OwnCloud server anymore and keeps on updating and updating without a result (and seemingly without giving up trying to update).
I activated logging and the last entry in the log files always is "Initializing folders model".

Best regards

**Comment by buschmann23** [comment] 2015-05-06 15:16
Thank you for your report. I will investigate this issue. My Jolla's display is currently broken and I am waiting for a new one. So I could not really test the currently release. But now, with SDK updated, I will test it there.

**Comment by buschmann23** [comment] 2015-05-06 16:23
I can not reproduce the error in the SDK virtualbox, but because of the SDK update, that was a fresh install there.

Can you please test the rebuilt package? There is nothing changed, only that I have rebuilt it on the current SDK version.

https://wolke.huessenbergnetz.de/index.php/s/Cmzpq9qP8abNtnJ

**Comment by rednaxela-work** [comment] 2015-05-06 17:18
Sorry, the updated package doesn't seem to change anything. Still the same hang situation in "Initializing folders model". :-(

**Comment by buschmann23** [comment] 2015-05-06 17:42
Are you using the folder or the feed view? Have you tried to restart the whole application, including the background daemon, by using quit from the main page pull down menu?

**Comment by rednaxela-work** [comment] 2015-05-06 18:02
I was using the folder view. After your hint on stopping the daemon (didn't notice the "Quite" menu entry before ;-) ) restarted ocNews completely.

This is the log when using folder view:
```
INFO  2015-05-06T19:51:14.259 Starting ocNews Reader version  1.9.4 
INFO  2015-05-06T19:51:14.259 Built with Qt 5.2.2 running on 5.2.2 
DEBUG 2015-05-06T19:51:14.267 Database file path:  "/home/nemo/.local/share/harbour-ocnews-reader/database.sqlite" 
INFO  2015-05-06T19:51:14.268 Opened sqlite database 
INFO  2015-05-06T19:51:14.299 ocNews Reader locale set to  "de_DE" 
DEBUG 2015-05-06T19:51:14.308 Folders model filter: set order by to  "title" 
DEBUG 2015-05-06T19:51:14.312 Combined model filter: Changed order by to  "title" 
DEBUG 2015-05-06T19:51:14.315 Feeds model filter: changed sort order to  "title" 
DEBUG 2015-05-06T19:51:14.319 Items model: changing showExcerpts to  true 
DEBUG 2015-05-06T19:51:15.042 Folder model: set active to  true 
INFO  2015-05-06T19:51:15.043 Clearing folders model 
INFO  2015-05-06T19:51:15.045 Initialize folders model 
```

Switched to feed view, quit ocNews completely and restarted. This is the log now:
```
INFO  2015-05-06T19:52:11.730 Starting ocNews Reader version  1.9.4 
INFO  2015-05-06T19:52:11.732 Built with Qt 5.2.2 running on 5.2.2 
DEBUG 2015-05-06T19:52:11.741 Database file path:  "/home/nemo/.local/share/harbour-ocnews-reader/database.sqlite" 
INFO  2015-05-06T19:52:11.745 Opened sqlite database 
INFO  2015-05-06T19:52:11.774 ocNews Reader locale set to  "de_DE" 
DEBUG 2015-05-06T19:52:11.783 Folders model filter: set order by to  "title" 
DEBUG 2015-05-06T19:52:11.787 Combined model filter: Changed order by to  "title" 
DEBUG 2015-05-06T19:52:11.790 Feeds model filter: changed sort order to  "title" 
DEBUG 2015-05-06T19:52:11.794 Items model: changing showExcerpts to  true 
DEBUG 2015-05-06T19:52:12.476 Combined model: set active to  true 
INFO  2015-05-06T19:52:12.478 Initialize combined model 
INFO  2015-05-06T19:52:12.479 Clearing combined model 
```

**Comment by buschmann23** [comment] 2015-05-06 18:09
Do you also have a log what happens, when you try to update the entries? Please have a look into the log before posting, maybe your password is not hidden properly in the logs. I found a few places where I forgot to hide the user's password in the output. :)

**Comment by buschmann23** [comment] 2015-05-06 18:15
Also that log is only the log of the reader app, not the engine/daemon log. :) It would be more important to me to have a log of the daemon. You can find them in /home/nemo/.local/share/harbour-ocnews-reader/logs , too. There are files names as ocnews-engine-.....log

**Comment by buschmann23** [comment] 2015-05-06 18:16
If you do not want to post that here, please send it via mail to me: kontakt ätät buschmann23 punkt de

**Comment by rednaxela-work** [comment] 2015-05-06 18:19
Odd thing is, I don't have an engine log at all. Rebooting my phone now to start everything anew.

The other thing is that there seems to be another bug in ocNews preventing me from trying to do a manual update. Even if I switch ocNews to only update everything manually it does it automatically after restart.

**Comment by rednaxela-work** [comment] 2015-05-06 18:20
But good news is, after a reboot - in best MS Windows tradition - ocNews is able again to connect to my OwnCloud instance and update feeds!! :-)

**Comment by rednaxela-work** [comment] 2015-05-06 18:22
And I have an engine log now, too.

Still a very odd situation... Seems the daemon somehow was hanging and the reader app couldn't access it... ?

**Comment by buschmann23** [comment] 2015-05-06 23:25
Nice to hear. :) So, might be, that the D-Bus communication had problems. If you want, you can still send the logs. Normally the reader communicates via D-Bus to the daemon/engine. So the engine performs all the tasks of updating and communicating with the server. But the reader has it's own access to the local database.

So, might be, that the daemon was somehow in caught in a loop, and was not able to talk to the reader. How do you fetch images? Do you fetch them while updating or on demand, when opening a news entry? Might be also an issue in that component.

**Comment by rednaxela-work** [comment] 2015-05-07 06:34
Sorry, already disabled logging and deleted the logs. And before rebooting the daemon didn't write log files. The latest reader log files are contained in the post above.

Regarding image loading, I've set it to load when opening the news entry,

Thanks for your quick support! Next time I'll first try to reboot the device before opening tickets... :-)

**Comment by buschmann23** [comment] 2015-05-07 08:36
No problem. :) So I will close this issue. Feel free to reopen it when the error occurs again.

**Closed by buschmann23** 2015-05-07 08:36 UTC
Labels: bug, investigating, Need more info, Sailfish OS
